# netlify.toml

[build]
  command = "pip install -r requirements.txt -t netlify/functions"
  functions = "netlify/functions"

# Add this entire section
[functions]
  # Include all necessary application files and folders
  included_files = [
      "app.py",
      "templates/**",
      "ai/**",
      "azure_integration/**",
      "config/**",
      "jira/**",
      "utils/**"
  ]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
